[package]
name = "serde-binprot"
version = "0.1.0"
authors = ["laurent <laurent.mazare@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1.0"
byteorder = "1"

[dev-dependencies]
serde_derive = "1.0"
